export const mockMasters = [
  { id: 1, code: "CAT-001", name: "Electronics", description: "Electronic devices and components", type: "Category", status: "Active" },
  { id: 2, code: "CAT-002", name: "Office Supplies", description: "Stationery and office equipment", type: "Category", status: "Active" },
  { id: 3, code: "CAT-003", name: "Furniture", description: "Desks, chairs, and storage", type: "Category", status: "Active" },
  { id: 4, code: "SUB-001", name: "Wireless Peripherals", description: "Mice, keyboards, and headsets", type: "SubCategory", status: "Active" },
  { id: 5, code: "SUB-002", name: "Monitors", description: "Display screens and mounts", type: "SubCategory", status: "Inactive" },
  { id: 6, code: "CAT-004", name: "Accessories", description: "Cables, cases, and adapters", type: "Category", status: "Active" },
  { id: 7, code: "CAT-005", name: "Storage", description: "SSDs, HDDs, and flash drives", type: "Category", status: "Active" },
  { id: 8, code: "SUB-003", name: "Ergonomic Seating", description: "Chairs and footrests", type: "SubCategory", status: "Active" },
  { id: 9, code: "CAT-006", name: "Wearables", description: "Bands, watches, and fitness gear", type: "Category", status: "Inactive" },
  { id: 10, code: "SUB-004", name: "Lighting", description: "Desk lamps and bulbs", type: "SubCategory", status: "Active" },
  { id: 11, code: "CAT-007", name: "Networking", description: "Routers, switches, and hubs", type: "Category", status: "Active" },
  { id: 12, code: "SUB-005", name: "Audio Equipment", description: "Speakers and microphones", type: "SubCategory", status: "Active" },
  { id: 13, code: "CAT-008", name: "Software Licenses", description: "Subscription and perpetual licenses", type: "Category", status: "Inactive" },
  { id: 14, code: "SUB-006", name: "Power & Charging", description: "Chargers and power banks", type: "SubCategory", status: "Active" },
  { id: 15, code: "CAT-009", name: "Printing", description: "Printers, ink, and paper", type: "Category", status: "Active" },
  { id: 16, code: "SUB-007", name: "Document Scanners", description: "Flatbed and sheet-fed scanners", type: "SubCategory", status: "Active" },
  { id: 17, code: "CAT-010", name: "Security", description: "Locks, cameras, and access control", type: "Category", status: "Inactive" },
  { id: 18, code: "SUB-008", name: "Tablet Accessories", description: "Cases, styluses, and stands", type: "SubCategory", status: "Active" },
];
