export const mockProducts = [
  { id: 1, sku: "SKU-101", name: "Wireless Mouse", price: 29.99, category: "Electronics" },
  { id: 2, sku: "SKU-102", name: "Mechanical Keyboard", price: 89.99, category: "Electronics" },
  { id: 3, sku: "SKU-103", name: "USB-C Hub", price: 45.5, category: "Accessories" },
  { id: 4, sku: "SKU-104", name: "Laptop Stand", price: 34.0, category: "Office" },
  { id: 5, sku: "SKU-105", name: "Noise-Canceling Headphones", price: 199.99, category: "Electronics" },
  { id: 6, sku: "SKU-106", name: "Webcam HD", price: 59.99, category: "Electronics" },
  { id: 7, sku: "SKU-107", name: "Desk Lamp LED", price: 24.99, category: "Office" },
  { id: 8, sku: "SKU-108", name: "Ergonomic Chair", price: 349.0, category: "Furniture" },
  { id: 9, sku: "SKU-109", name: "Monitor 27 inch", price: 279.99, category: "Electronics" },
  { id: 10, sku: "SKU-110", name: "External SSD 1TB", price: 119.99, category: "Storage" },
  { id: 11, sku: "SKU-111", name: "Phone Charger", price: 19.99, category: "Accessories" },
  { id: 12, sku: "SKU-112", name: "Bluetooth Speaker", price: 49.99, category: "Electronics" },
  { id: 13, sku: "SKU-113", name: "Notebook Pack", price: 12.5, category: "Office" },
  { id: 14, sku: "SKU-114", name: "Standing Desk", price: 499.0, category: "Furniture" },
  { id: 15, sku: "SKU-115", name: "Tablet Case", price: 22.99, category: "Accessories" },
  { id: 16, sku: "SKU-116", name: "Graphics Tablet", price: 159.99, category: "Electronics" },
  { id: 17, sku: "SKU-117", name: "Cable Organizer", price: 8.99, category: "Accessories" },
  { id: 18, sku: "SKU-118", name: "Smart Watch Band", price: 15.99, category: "Wearables" },
  { id: 19, sku: "SKU-119", name: "Portable Power Bank", price: 39.99, category: "Electronics" },
  { id: 20, sku: "SKU-120", name: "Document Scanner", price: 129.0, category: "Office" },
  { id: 21, sku: "SKU-121", name: "Phone Charger", price: 19.99, category: "Accessories" },
  { id: 22, sku: "SKU-122", name: "Bluetooth Speaker", price: 49.99, category: "Electronics" },
  { id: 23, sku: "SKU-123", name: "Notebook Pack", price: 12.5, category: "Office" },
  { id: 24, sku: "SKU-124", name: "Standing Desk", price: 499.0, category: "Furniture" },
  { id: 25, sku: "SKU-125", name: "Tablet Case", price: 22.99, category: "Accessories" },
];
