export const mockPromotions = [
  {
    id: 1,
    name: "Summer Sale",
    description: "20% off all items",
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    discountType: "Percentage",
    discountValue: 20,
    status: "Active",
  },
  {
    id: 2,
    name: "Black Friday Sale",
    description: "30% off electronics and accessories",
    startDate: "2024-11-25",
    endDate: "2024-11-30",
    discountType: "Percentage",
    discountValue: 30,
    status: "Upcoming",
  },
  {
    id: 3,
    name: "Back to School",
    description: "15% off office supplies and furniture",
    startDate: "2024-08-01",
    endDate: "2024-09-30",
    discountType: "Percentage",
    discountValue: 15,
    status: "Active",
  },
  {
    id: 4,
    name: "New Year Flash Sale",
    description: "Flat $50 off on orders above $200",
    startDate: "2025-01-01",
    endDate: "2025-01-03",
    discountType: "Fixed Amount",
    discountValue: 50,
    status: "Draft",
  },
  {
    id: 5,
    name: "Winter Clearance",
    description: "40% off winter collection",
    startDate: "2024-01-15",
    endDate: "2024-02-15",
    discountType: "Percentage",
    discountValue: 40,
    status: "Expired",
  },
  {
    id: 6,
    name: "Free Shipping Weekend",
    description: "Free shipping on all orders",
    startDate: "2024-07-12",
    endDate: "2024-07-14",
    discountType: "Fixed Amount",
    discountValue: 0,
    status: "Expired",
  },
  {
    id: 7,
    name: "Spring Refresh",
    description: "Buy 2 Get 1 Free on accessories",
    startDate: "2024-03-20",
    endDate: "2024-04-20",
    discountType: "Percentage",
    discountValue: 33,
    status: "Expired",
  },
  {
    id: 8,
    name: "Member Exclusive",
    description: "$25 off for premium members",
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    discountType: "Fixed Amount",
    discountValue: 25,
    status: "Upcoming",
  },
  {
    id: 9,
    name: "Holiday Bundle",
    description: "Bundle pack at 25% discount",
    startDate: "2024-12-15",
    endDate: "2024-12-25",
    discountType: "Percentage",
    discountValue: 25,
    status: "Upcoming",
  },
  {
    id: 10,
    name: "Mega Monday",
    description: "50% off selected items",
    startDate: "2024-04-01",
    endDate: "2024-04-01",
    discountType: "Percentage",
    discountValue: 50,
    status: "Expired",
  },
  {
    id: 11,
    name: "Tech Tuesday",
    description: "Flat $100 off on laptops",
    startDate: "2024-09-10",
    endDate: "2024-09-10",
    discountType: "Fixed Amount",
    discountValue: 100,
    status: "Expired",
  },
  {
    id: 12,
    name: "Weekend Warrior",
    description: "10% off everything this weekend",
    startDate: "2024-05-18",
    endDate: "2024-05-19",
    discountType: "Percentage",
    discountValue: 10,
    status: "Expired",
  },
  {
    id: 13,
    name: "Clearance Extravaganza",
    description: "Up to 60% off clearance items",
    startDate: "2024-10-01",
    endDate: "2024-10-31",
    discountType: "Percentage",
    discountValue: 60,
    status: "Expired",
  },
  {
    id: 14,
    name: "Loyalty Reward",
    description: "Free gift with purchase over $150",
    startDate: "2024-11-01",
    endDate: "2024-11-30",
    discountType: "Fixed Amount",
    discountValue: 0,
    status: "Upcoming",
  },
  {
    id: 15,
    name: "Early Bird Special",
    description: "20% off on all pre-orders",
    startDate: "2025-02-01",
    endDate: "2025-02-28",
    discountType: "Percentage",
    discountValue: 20,
    status: "Draft",
  },
];